[general]
import = [
  "theme.toml",
]

[window]

opacity = 1

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark" # "Dark"

[font]

normal.family = "Agave"
bold.family = "Agave"
italic.family = "Agave"

size = 16.0
