[general]
import = [
  "theme.toml",
]

[window]

opacity = 1

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark" # "Dark"

[font]

normal.family = "AtkynsonMono Nerd Font Mono"
bold.family = "AtkynsonMono Nerd Font Mono"
italic.family = "AtkynsonMono Nerd Font Mono"

size = 14.0
